// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int32
	Name        pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsActive    pgtype.Bool
}

type Customer struct {
	ID           int32
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsActive     pgtype.Bool
}

type Order struct {
	ID          int32
	CustomerID  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TotalAmount pgtype.Numeric
	Status      string
	IsActive    pgtype.Bool
}

type OrderItem struct {
	ID        int32
	OrderID   pgtype.Int4
	ProductID pgtype.Int4
	Quantity  int32
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Payment struct {
	ID            int32
	OrderID       pgtype.Int4
	Amount        pgtype.Numeric
	Method        string
	Status        string
	TransactionID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Product struct {
	ID          int32
	Name        pgtype.Text
	Description pgtype.Text
	Price       pgtype.Numeric
	CategoryID  pgtype.Int4
	Quantity    pgtype.Int4
	Rating      pgtype.Numeric
	Image       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsActive    pgtype.Bool
}
