// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price, created_at, updated_at
`

type AddOrderItemParams struct {
	OrderID   pgtype.Int4
	ProductID pgtype.Int4
	Quantity  int32
	Price     pgtype.Numeric
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price, oi.created_at, oi.updated_at, p.name, p.image 
FROM order_items oi
JOIN product p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type ListOrderItemsRow struct {
	ID        int32
	OrderID   pgtype.Int4
	ProductID pgtype.Int4
	Quantity  int32
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
	Image     pgtype.Text
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.Int4) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
