// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, total_amount, status)
VALUES ($1, $2, $3)
RETURNING id, customer_id, created_at, updated_at, total_amount, status, is_active
`

type CreateOrderParams struct {
	CustomerID  pgtype.Int4
	TotalAmount pgtype.Numeric
	Status      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.CustomerID, arg.TotalAmount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.Status,
		&i.IsActive,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, created_at, updated_at, total_amount, status, is_active FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.Status,
		&i.IsActive,
	)
	return i, err
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, customer_id, created_at, updated_at, total_amount, status, is_active FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID pgtype.Int4) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.Status,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
