// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, amount, method, status, transaction_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, amount, method, status, transaction_id, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID       pgtype.Int4
	Amount        pgtype.Numeric
	Method        string
	Status        string
	TransactionID pgtype.Text
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.Method,
		arg.Status,
		arg.TransactionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT id, order_id, amount, method, status, transaction_id, created_at, updated_at FROM payments
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrder(ctx context.Context, orderID pgtype.Int4) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
