// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (name, description, price, category_id, quantity, rating, image)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, price, category_id, quantity, rating, image, created_at, updated_at, is_active
`

type CreateProductParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	Price       pgtype.Numeric
	CategoryID  pgtype.Int4
	Quantity    pgtype.Int4
	Rating      pgtype.Numeric
	Image       pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.Quantity,
		arg.Rating,
		arg.Image,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Quantity,
		&i.Rating,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, category_id, quantity, rating, image, created_at, updated_at, is_active FROM product
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Quantity,
		&i.Rating,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, category_id, quantity, rating, image, created_at, updated_at, is_active FROM product
WHERE is_active = true
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Quantity,
			&i.Rating,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE product
SET quantity = quantity - $2, updated_at = now()
WHERE id = $1 AND quantity >= $2
`

type UpdateProductStockParams struct {
	ID       int32
	Quantity pgtype.Int4
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.Quantity)
	return err
}
